-- 기존 테이블 백업 (필요시)
-- CREATE TABLE hk_users_backup AS SELECT * FROM hk_users;

-- 통합된 사용자 테이블 (기존 데이터 보존하며 컬럼 추가)
DROP TABLE hk_users CASCADE CONSTRAINTS;
DROP TABLE hk_user_auth CASCADE CONSTRAINTS;
DROP TABLE hk_social_users CASCADE CONSTRAINTS;

CREATE TABLE hk_users (
    user_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(50) UNIQUE NOT NULL,        -- 로그인용 아이디
    username VARCHAR2(50) NOT NULL,              -- 닉네임  
    email VARCHAR2(100) UNIQUE NOT NULL,         -- 이메일 (분리)
    phone VARCHAR2(20) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,             -- BCrypt 암호화 지원
    profile_image VARCHAR2(200) DEFAULT 'avatar1.png',
    birth_date DATE,
    gender VARCHAR2(10),
    join_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(20) DEFAULT 'ACTIVE'
);

-- 사용자 인증 테이블 (SMS, 이메일 인증용)
CREATE TABLE hk_user_auth (
    auth_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_num NUMBER NOT NULL,
    auth_type VARCHAR2(20) NOT NULL, -- 'SMS', 'EMAIL'
    auth_code VARCHAR2(6) NOT NULL,
    expire_time TIMESTAMP NOT NULL,
    is_verified CHAR(1) DEFAULT 'N',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_num) REFERENCES hk_users(user_num)
);

-- 소셜 로그인 테이블
CREATE TABLE hk_social_users (
    social_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_num NUMBER NOT NULL,
    provider VARCHAR2(20) DEFAULT 'NAVER',
    social_user_id VARCHAR2(100) NOT NULL,
    FOREIGN KEY (user_num) REFERENCES hk_users(user_num)
);

-- 로그인 반복 시도 차단 IP 테이블
CREATE TABLE hk_ban_ip(
    ip VARCHAR2(50) PRIMARY KEY,
    cnt NUMBER DEFAULT 1,
    ban_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
