server.port=8080
server.servlet.context-path=/hellking

server.address=0.0.0.0
server.jsp.init-parameters.development=false

logging.level.net.koreate.hellking=DEBUG
logging.level.org.mybatis=DEBUG

kakao.map.api-key=e9b67200244ba257199ebb728770b0a8
kakao.map.rest-api-key=4ffce2de3af6d9e5c21054297e5b4480

map.default.latitude=37.5665
map.default.longitude=126.9780
map.default.zoom=3

